Us004 view band level
steveh2707/IWantItDataWay-API pull request #9
Opened 2023-11-16 10:11 UTC by steveh2707

2023-11-16 16:30 UTC, glenn-hamilton requested changes

2023-11-16 16:30 UTC, glenn-hamilton commented on sql-scripts/US004-view-band-level.sql
> +	band_id tinyint unsigned AUTO_INCREMENT,
The bands are specific, so it might not be best to have these as auto increment

2023-11-16 16:30 UTC, glenn-hamilton commented on src/main/java/org/kainos/ea/db/BandDao.java
> +                    "FROM band ";
`;` at the end of the query

2023-11-17 12:11 UTC, DarraghHaughey-Kainos approved these changes
Love it!

2023-11-17 14:33 UTC, glenn-hamilton commented on sql-scripts/US004-view-band-level.sql
> +INSERT INTO band (band_id, band_name) VALUES (1,"Apprentice"), (2,"Trainee"), (3,"Associate"), (4,"Senior Associate"), (5,"Consultant"), (6,"Manager"), (7,"Principal"), (8,"Leadership Community");
I can't remember what we discussed the other day, but the band numbers go the opposite direction

2023-11-17 14:45 UTC, steveh2707 commented on sql-scripts/US004-view-band-level.sql
> +INSERT INTO band (band_id, band_name) VALUES (1,"Apprentice"), (2,"Trainee"), (3,"Associate"), (4,"Senior Associate"), (5,"Consultant"), (6,"Manager"), (7,"Principal"), (8,"Leadership Community");
Hi Glenn, these are not publically viewable and will only be used for API id endpoints.

2023-11-20 08:45 UTC, glenn-hamilton approved these changes

2023-11-20 08:45 UTC, glenn-hamilton commented on sql-scripts/US004-view-band-level.sql
> +INSERT INTO band (band_id, band_name) VALUES (1,"Apprentice"), (2,"Trainee"), (3,"Associate"), (4,"Senior Associate"), (5,"Consultant"), (6,"Manager"), (7,"Principal"), (8,"Leadership Community");
In that case it might be best to change the ID back to an auto increment value (I know I asked for it not to be that before 😅)

2023-11-21 09:07 UTC, merged